In [ ]:
from google.colab import drive
drive.mount("/content/drive")

In [ ]:
import keras
import sklearn
import pandas as pd
import numpy as np


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from __future__ import print_function


In [ ]:
pd.options.display.max_rows = 10
pd.options.display.float_format = "{:.1f}".format
np.set_printoptions(linewidth = 200)
from IPython.display import display, HTML

In [ ]:
from collections import defaultdict
from pathlib import Path

In [ ]:
trainDataPath = "/content/drive/MyDrive/Datasets MNIST/digits/trainingDigits"
testDataPath = "/content/drive/MyDrive/Datasets MNIST/digits/testDigits"


TypeError: ignored

In [ ]:
results = defaultdict(list)
for file in Path(trainDataPath).iterdir():
    with open(file, "r") as file_open:
        results["text"].append(file_open.read())
train_df_feature = pd.DataFrame(results)
print(train_df_feature) #this will be feature of training dataset


                                                   text
0     00000000000001111000000000000000\n000000000000...
1     00000000000001111111000000000000\n000000000001...
2     00000000001000000000100000000000\n000000011111...
3     00000000000000001111100000000000\n000000000000...
4     00000000000000000111111110000000\n000000000011...
...                                                 ...
1939  00000000000000001110000000000000\n000000000000...
1940  00000000000000111000000000000000\n000000000000...
1941  00000000000000000111100000000000\n000000000000...
1942  00000000000000001000000000000000\n000000000000...
1943  00000000001111111111100000000000\n000000000111...

[1944 rows x 1 columns]


In [ ]:
label =[]
for file in Path(trainDataPath).iterdir():
  label.append(str(str(file).split("/")[-1]).split(".")[0][0]) #extracting the labels from .txt file name. eg.(1_92.txt = 1)
print(label)
train_df_label = pd.DataFrame(label) #this will be label dataset
    

['4', '3', '5', '7', '5', '9', '8', '0', '8', '7', '9', '7', '8', '1', '0', '5', '9', '6', '1', '2', '8', '6', '8', '1', '5', '2', '8', '7', '3', '1', '7', '6', '0', '6', '5', '3', '5', '1', '8', '7', '3', '6', '1', '3', '0', '4', '3', '7', '0', '6', '9', '4', '5', '7', '1', '0', '4', '3', '3', '0', '3', '1', '4', '2', '5', '5', '5', '5', '7', '0', '6', '6', '0', '2', '6', '0', '3', '9', '7', '0', '3', '4', '8', '7', '2', '2', '2', '4', '4', '5', '3', '1', '3', '0', '3', '4', '1', '1', '9', '7', '4', '3', '6', '3', '1', '2', '0', '9', '9', '1', '3', '9', '7', '7', '3', '7', '0', '7', '2', '0', '3', '2', '5', '0', '1', '9', '6', '3', '6', '5', '1', '6', '2', '9', '3', '3', '1', '7', '4', '9', '8', '5', '1', '2', '2', '2', '6', '2', '0', '4', '2', '8', '0', '9', '4', '8', '0', '1', '8', '3', '5', '1', '9', '3', '9', '0', '3', '0', '5', '8', '1', '6', '2', '9', '9', '9', '9', '6', '2', '9', '4', '6', '8', '1', '1', '6', '0', '5', '6', '2', '7', '7', '3', '3', '1', '0', '3', '0', '0', '1',

In [ ]:
print(train_df_label)

      0
0     4
1     3
2     5
3     7
4     5
...  ..
1939  0
1940  9
1941  5
1942  6
1943  5

[1944 rows x 1 columns]


In [ ]:
#similarly for test feature and labels
results_T = defaultdict(list)
label_T=[]
for file in Path(testDataPath).iterdir():
    with open(file, "r") as file_open:
        results_T["text"].append(file_open.read())
    label_T.append(str(str(file).split("/")[-1]).split(".")[0][0])
test_df_feature = pd.DataFrame(results_T)
test_df_label=pd.DataFrame(label_T)


In [ ]:
print(test_df_feature)

                                                  text
0    00000000011111100000000000000000\n000000011111...
1    00000000000000000111100000000000\n000000000000...
2    00000000000000001000000000000000\n000000000000...
3    00000000000000011111000000000000\n000000000000...
4    00000000000000001110000000000000\n000000000000...
..                                                 ...
951  00000000000011111100000000000000\n000000000011...
952  00000000000001110000000000000000\n000000000000...
953  00000000000000111110000000000000\n000000000000...
954  00000000000111000000000000000000\n000000000011...
955  00000000000000000111111000000000\n000000000000...

[956 rows x 1 columns]


In [ ]:
print(test_df_label)

     0
0    3
1    8
2    8
3    2
4    4
..  ..
951  8
952  6
953  4
954  0
955  7

[956 rows x 1 columns]


In [ ]:
#giving viable column names to respective datasets
test_df_label.columns = ["label"]
train_df_label.columns = ["label"]
test_df_feature.columns=["feature"]
train_df_feature.columns=["feature"]

In [ ]:
#using regex for removing "\n" from data

train_df_feature=train_df_feature.replace('\n','',regex=True)
train_df_label=train_df_label.replace('\n','',regex=True)
test_df_label=test_df_label.replace('\n','',regex=True)
test_df_feature=test_df_feature.replace('\n','',regex=True)

In [ ]:
test_features=test_df_feature.feature.astype(str).apply(list).apply(pd.Series).astype(int)
test_feature_dataframe = pd.DataFrame(test_features)
train_features = train_df_feature.feature.astype(str).apply(list).apply(pd.Series).astype(int)
train_features_dataframe = pd.DataFrame(train_features)

In [ ]:
print(test_feature_dataframe.head())
print(train_features_dataframe.head())

   0     1     2     3     4     5     ...  1018  1019  1020  1021  1022  1023
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 1024 columns]
   0     1     2     3     4     5     ...  1018  1019  1020  1021  1022  1023
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 1024 columns]


In [ ]:
#we are ready to go with, train_df_feature, train_df_label, test_df_feature, test_df_label
x_train= train_features_dataframe[train_features_dataframe.columns[1:1024]]
y_train=train_df_label["label"]
x_test=test_feature_dataframe[test_feature_dataframe.columns[1:1024]]
y_test=test_df_label["label"]

In [ ]:
print(x_train.head())
print(y_train.head())
print(x_test.head())
print(y_test.head())

   1     2     3     4     5     6     ...  1018  1019  1020  1021  1022  1023
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 1023 columns]
0    4
1    3
2    5
3    7
4    5
Name: label, dtype: object
   1     2     3     4     5     6     ...  1018  1019  1020  1021  1022  1023
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...  

In [ ]:
knn=KNeighborsClassifier(n_neighbors = 3)

In [ ]:
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
predictions = knn.predict(x_test)
print(predictions[1])



8


In [ ]:
print("Evaluating on testing data")
print(classification_report(y_test, predictions))

print ("Confusion matrix")
print(confusion_matrix(y_test,predictions))

Evaluating on testing data
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        87
           1       0.96      0.99      0.97        97
           2       1.00      1.00      1.00        92
           3       0.98      0.99      0.98        85
           4       1.00      1.00      1.00       114
           5       0.99      0.98      0.99       108
           6       0.98      1.00      0.99        97
           7       0.98      1.00      0.99        96
           8       1.00      0.95      0.97        91
           9       0.99      0.97      0.98        89

    accuracy                           0.99       956
   macro avg       0.99      0.99      0.99       956
weighted avg       0.99      0.99      0.99       956

Confusion matrix
[[ 87   0   0   0   0   0   0   0   0   0]
 [  0  96   0   0   0   0   0   1   0   0]
 [  0   0  92   0   0   0   0   0   0   0]
 [  0   0   0  84   0   0   0   0   0   1]
 [  0   0   0   0 114   0